name: deploy gh-pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : onon1101
      USER_EMAIL  : mingzhuguly@gmain.com
      PUBLISH_DIR : ./doc_build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: npm run build
      run: |
        npm run build
    - name: Commit files
      run: |
        cd $PUBLISH_DIR
        git init
        git config --global init.defaultBranch main
        git config --local user.name $USER_NAME
        git config --local user.email $USER_EMAIL
        git status
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout -b gh-pages
        git add --all
        git commit -m "deploy to Github pages"
        git push origin gh-pages -f
        echo 🤘 deploy gh-pages complete.
